[book]
authors = ["Nur"]
language = "en"
multilingual = false
src = "src"
title = "CSE Note"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/nurmohammed840/cse-note"
edit-url-template = "https://github.com/nurmohammed840/cse-note/edit/main/{path}"